#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@xunlei[-1]
	add ucitrack xunlei
	set ucitrack.@xunlei[-1].init=xunlei
	commit ucitrack
EOF

[ ! -f /etc/synoinfo.conf ] && echo "unique=\"synology_$(cat /proc/sys/kernel/random/uuid | cut -c1-7)_720+\"" > /etc/synoinfo.conf

rm -rf /tmp/luci-*
exit 0
